### ISSUE TITLE
多平台音乐播放APlayer - 支持https | Fayne's Blog

### ISSUE THREAD

**Issue by fanjinhao** [fanjinhao/fanjinhao.github.io#44]
https://www.fayne.cn/2017/12/09/aplayer/

**Comment by tl-Tangliang** [comment]
首页布局是哪个配置文件呢？没找到，我也想首页标题居中

**Comment by fanjinhao** [comment]
我是直接把next/layout/_partials/footer.swig文件中的div标签给居中了，其实也是不用这么麻烦的，直接找到底部的标签，chrome中右键检查选项，找到对应的标签，然后设置成想要的样式就好了，然后把样式代码放在next/source/css/_custom/custiom.styl中就好了，这个自定义样式的优先级比较高，改错了也容易复原
